### ISSUE TITLE
arm64 image tagged as amd64

### ISSUE THREAD

**Issue by dvdjaco** [zk-org/zk-xcompile#1]
When trying to build for `amd64` I get the error below because the image is actually arm64/V8. I was able to build the amd64 image locally.

```
$ docker run --platform linux/amd64 --rm -v "${PWD}":/usr/src/zk -w /usr/src/zk mickaelmenu/zk-xcompile:linux-amd64 /bin/bash -c 'make'
Unable to find image 'mickaelmenu/zk-xcompile:linux-amd64' locally
linux-amd64: Pulling from mickaelmenu/zk-xcompile
Digest: sha256:5888bd7ecc5961f4a636c2697f4313ca9f4df3442baa1b0c99b35ede5402853c
Status: Image is up to date for mickaelmenu/zk-xcompile:linux-amd64
docker: Error response from daemon: image with reference mickaelmenu/zk-xcompile:linux-amd64 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8.
See 'docker run --help'.
```

**Comment by mickael-menu** [comment]
I'm not sure how to fix this, as I'm no Docker expert. Any suggestion?

**Comment by dvdjaco** [comment]
The command in the README looks ok, the `-t mickaelmenu/zk-xcompile:linux-amd64` option tells docker to label the image with the `name:tag` in the argument. I'm guessing that the last time the _amd64_ image was built and uploaded to the registry the command got messed up and it was incorrectly tagged as _arm64_ instead.

Repeating the build & push steps with the correct tag should fix it:
```
docker build -t mickaelmenu/zk-xcompile:linux-amd64 ./linux-amd64
docker push mickaelmenu/zk-xcompile:linux-amd64
```

**Comment by mickael-menu** [comment]
I just did, let me know if it fixes the issue for you.

**Comment by mickael-menu** [comment]
I see that it is still marked as `linux/arm64/v8` 🤷‍♂️ 

https://hub.docker.com/layers/mickaelmenu/zk-xcompile/linux-amd64/images/sha256-6d727ac5309cf98f7b9ecbf2082ac3a2b8dd0b85e7d86833946460ed35954e6f?context=repo
<img width="630" alt="Screenshot 2022-09-27 at 17 29 44" src="https://user-images.githubusercontent.com/58686775/192569569-6e311b37-bde6-4bac-b123-e2d7662698e8.png">

The other images have the same platform, including the `i386` one.

**Comment by dvdjaco** [comment]
I see! I don't usually build different images for different platforms, so I didn't think of this issue. Docker will build for the platform defined in the env variable `DOCKER_DEFAULT_PLATFORM`, regardless of the os/arch labels in the Dockerfile. To change it for each build, you can either change the environment variable before running `docker build`, or add the `--platform` flag to the `FROM` line in each Dockerfile, e.g.:
```
FROM --platform linux/amd64 golang:1.18
```

**Comment by mickael-menu** [comment]
Thank you, it looks like it worked and now I'm able to compile the binaries for Linux! Thanks a lot for your help.
